-- ============================================================
-- CUSTOMER REPORT
-- ============================================================
-- Purpose:
-- This report consolidates key customer metrics and behaviors.
--
-- Highlights:
-- 1. Retrieves essential customer and transaction information.
-- 2. Segments customers into VIP, Regular, and New.
-- 3. Groups customers by age.
-- 4. Aggregates customer-level metrics:
--    - total orders
--    - total sales
--    - total quantity purchased
--    - total products purchased
--    - customer lifespan
-- 5. Calculates additional KPIs:
--    - recency
--    - average order value
--    - average monthly spend
-- ============================================================
CREATE OR REPLACE VIEW gold.report_customers AS
-- ============================================================
-- 1) BASE QUERY
-- Retrieves core columns from the fact and customer dimension tables.
-- ============================================================
WITH base_query AS (

    SELECT
        a.order_number,
        a.product_key,
        a.order_date,
        a.sales_amount,
        a.quantity,
        b.customer_key,
        b.customer_number,
        CONCAT(b.first_name, ' ', b.last_name) AS customer_name,
        -- Calculate the customer's current age.
        EXTRACT(YEAR FROM AGE(CURRENT_DATE, b.birthdate))::INT AS age
    FROM gold.fact_sales a
    LEFT JOIN gold.dim_customers b ON a.customer_key = b.customer_key
    WHERE a.order_date IS NOT NULL
),
-- ============================================================
-- 2) CUSTOMER AGGREGATION
-- Summarizes key metrics at the customer level.
-- Each row represents one customer.
-- ============================================================
customer_aggregation AS (
    SELECT
        customer_key,
        customer_number,
        customer_name,
        age,
        -- Number of unique orders made by the customer.
        COUNT(DISTINCT order_number) AS total_orders,
        -- Total revenue generated by the customer.
        SUM(sales_amount) AS total_sales,
        -- Total number of units purchased.
        SUM(quantity) AS total_quantity,
        -- Number of unique products purchased.
        COUNT(DISTINCT product_key) AS total_products,
        -- Most recent order date.
        MAX(order_date) AS last_order_date,
        -- Customer lifespan in months.
        (EXTRACT(YEAR FROM AGE(MAX(order_date),MIN(order_date))) * 12 + EXTRACT(MONTH FROM AGE(MAX(order_date),MIN(order_date))))::INT AS lifespan
    FROM base_query
    GROUP BY customer_key, customer_number, customer_name, age
)
-- ============================================================
-- 3) FINAL CUSTOMER REPORT
-- Adds customer segments, age groups, and analytical KPIs.
-- ============================================================
SELECT
    customer_key,
    customer_number,
    customer_name,
    age,
    CASE
        WHEN age < 20 THEN 'Under 20'
        WHEN age BETWEEN 20 AND 29 THEN '20-29'
        WHEN age BETWEEN 30 AND 39 THEN '30-39'
        WHEN age BETWEEN 40 AND 49 THEN '40-49'
        ELSE '50 and above'
    END AS age_group,
    CASE
		WHEN lifespan >= 12 AND total_sales > 5000 THEN 'VIP'
        WHEN lifespan >= 12 AND total_sales <= 5000 THEN 'Regular'
        ELSE 'New'
    END AS customer_segment,
    last_order_date,
    (EXTRACT(YEAR FROM AGE(CURRENT_DATE, last_order_date)) * 12 + EXTRACT(MONTH FROM AGE(CURRENT_DATE, last_order_date)))::INT AS recency,
    total_orders,
    total_sales,
    total_quantity,
    total_products,
    lifespan,
    CASE
        WHEN total_orders = 0 THEN 0
        ELSE total_sales / total_orders
    END AS avg_order_value,
    CASE
        WHEN lifespan = 0 THEN total_sales
        ELSE total_sales / lifespan
    END AS avg_monthly_spend
FROM customer_aggregation;
